# Font Settings
font_family      JetBrainsMono Nerd Font Mono
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        12.0
disable_ligatures always

# Window Aesthetics
window_padding_width 20
hide_window_decorations yes

# Color Palette (Solarized light)
background            #fdf6e3
foreground            #657b83
cursor                #586e75
selection_background  #475b62
selection_foreground  #eae3cb

# Normal Colors
color0  #eee8d5
color1  #dc322f
color2  #859900
color3  #b58900
color4  #268bd2
color5  #d33682
color6  #2aa198
color7  #073642

# Bright Colors
color8  #fdf6e3
color9  #cb4b16
color10 #93a1a1
color11 #839496
color12 #657b83
color13 #6c71c4
color14 #586e75
color15 #002b36

allow_remote_control yes
listen_on unix:/tmp/kitty