# Font Settings
font_family      JetBrainsMono Nerd Font Mono
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        11.0

# Window Aesthetics
window_padding_width 20
hide_window_decorations yes

# Color Palette (Gruvbox Material Dark / Evergreen Minimal)
background            #111211
foreground            #dfdbd2
cursor                #dfdbd2
selection_background  #4c4c4c
selection_foreground  #dfdbd2

# Normal Colors
color0  #232422
color1  #e67e80
color2  #a7c080
color3  #dbbc7f
color4  #7fbbb3
color5  #d699b6
color6  #83c092
color7  #dfdbd2

# Bright Colors
color8  #5c605e
color9  #e67e80
color10 #a7c080
color11 #dbbc7f
color12 #7fbbb3
color13 #d699b6
color14 #83c092
color15 #dfdbd2

allow_remote_control yes
listen_on unix:/tmp/kitty