github.com:
    users:
        amnxd:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: amnxd
