general {
    lock_cmd = pidof hyprlock || hyprlock       # 如何锁屏
    before_sleep_cmd = loginctl lock-session    # 睡眠前先锁屏
    after_sleep_cmd = hyprctl dispatch dpms on  # 唤醒后点亮屏幕
}

listener {
    timeout = 300                                # 5分钟 (300秒)
    on-timeout = hyprctl dispatch dpms off       # 关闭屏幕显示器
    on-resume = hyprctl dispatch dpms on         # 恢复动作点亮屏幕
}

listener {
    timeout = 600                                # 10分钟 (600秒)
    on-timeout = loginctl lock-session           # 执行锁屏
}

listener {
    timeout = 1800                               # 30分钟
    on-timeout = systemctl suspend               # 系统进入睡眠模式
}
