# Autostart commands and startup services
exec-once = swaync
exec-once = QML2_IMPORT_PATH=~/.config/quickshell/dynamic_island quickshell -p ~/.config/quickshell/dynamic_island/shell.qml
exec-once = sh -c 'if ! pgrep -x awww-daemon >/dev/null; then awww-daemon >/dev/null 2>&1 & sleep 1; fi; awww img "$HOME/.config/hypr/wallpaper.png"'
exec-once = fcitx5 -d
exec-once = waypaper --restore
exec-once = hypridle
exec-once = gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
exec-once = gsettings set org.gnome.desktop.interface gtk-theme 'Adwaita-dark'
exec-once = [workspace special:scratchpad silent] kitty --class kitty-scratchpad
