# General Hyprland layout and workspace behavior
general {
    gaps_in = 5
    gaps_out = 3, 10, 10, 10
    border_size = 0
    col.active_border = $color4
    col.inactive_border = $color0
    resize_on_border = false
    allow_tearing = true
    layout = dwindle
}

decoration {
    rounding = 15
    rounding_power = 4
    active_opacity = 1
    inactive_opacity = 1

    shadow {
        enabled = true
        range = 12
        render_power = 3
        color = rgba(444444aa)
    }

    blur {
        enabled = true
        size = 8
        passes = 3
        new_optimizations = true
        ignore_opacity = false
        vibrancy = 0.1696
        special = false
    }
}

cursor {
    no_hardware_cursors = false
}

misc {
    force_default_wallpaper = -1
    disable_hyprland_logo = false
}

dwindle {
    pseudotile = true
    preserve_split = true
}

master {
    new_status = master
}
