# Touch gestures and pointer device tuning
gesture = 3, horizontal, workspace
gesture = 3, up, special, workspace_name=scratchpad
gesture = 3, down, special, workspace_name=scratchpad
gesture = 2, pinch, cursorZoom, zoom_level=1, mode=live

device {
    name = epic-mouse-v1
    sensitivity = 3.0
}
