# Keyboard and touchpad input settings
input {
    kb_layout = us
    accel_profile = flat
    follow_mouse = 1
    sensitivity = 7.0

    touchpad {
        natural_scroll = true
        scroll_factor = 10.0
    }
}
