# Window rules for scratchpads and special windows
windowrule {
    name = kitty-scratchpad-rules
    match:class = ^(kitty-scratchpad)$
    float = true
    workspace = special:scratchpad silent
    size = 80% 55%
    move = 10% 40
    rounding = 14
    opacity = 0.90 0.90
}

windowrule {
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false
    no_focus = true
}

windowrule {
    name = move-hyprland-run
    match:class = hyprland-run
    move = 20 monitor_h-120
    float = yes
}
